### ISSUE TITLE
savestates don't save the complete state

### ISSUE THREAD

**Issue by notaz** [irixxxx/picodrive#166]
After reading [this post](https://github.com/TASEmulators/BizHawk/issues/2898#issuecomment-908640131) it's quite clear why TAS people don't want to update the core - savestate handling in the core is poor. While making TASes they need to save/load thousands of times, and if something isn't saved they get a desync.

It's not hard to see how bad it is by just using RetroArch's "Run-Ahead" feature (Settings->Latency, also make sure to disable "Use second instance"). It runs some frames ahead and then repeatedly loads a state to give an impression of lower input latency.

With this OD2 demo effects get broken and the demo eventually goes to "OD2 BSOD", 32X doesn't work at all, even Sonic1 has completely broken sound.

From quick look at the code, things like `PicoTiming`, `PicoSound`, `PicoEState` don't get saved, there are new globals like `VdpFIFO` that should go to `Pico` and then be properly saved in new savestate blocks IMO.

**Comment by irixxxx** [comment]
IMO, state saving has probably always been the weak spot in PicoDrive. It's a total mess, and it should be completely rewritten. Let's just start with it not being compatible between 32 bit and 64 bit systems, let alone big/little endian.
I have ideas for how I'd tackle this, however it's a lot of work and I just haven't come around to do it yet. It would need some work on most files in the pico and cpu subdirectories, besides it would difficult to keep it backwards compatible.


BTW, PicoTiming etc never got saved right back to the old days. IIRC some of them don't need it (e.g. PicoEState), and some of them have their data copied elsewhere (e.g. PicoTiming goes to the CPU states).

VdpFIFO is something new and has that TODO for saving since ages. There's some code to save crucial parts of that data the old way, but that's only a kludge, though it works well enough. There rarely is FIFO data to save at frame start, and that's even mostly the case in Overdrive2. I tried saving the complete structure, but it won't solve it for Overdrive2.


Run-ahead never has properly worked due to all this, right back to old versions of 1.93 and earlier. Part of the cycle information for the CPUs hadn't been saved.

**Comment by notaz** [comment]
Not sure if savestate portability between systems is really needed, at least it felt to me people aren't expecting it. And we've already broken compatibility between versions several times (my old 1.9x savestates result in broken graphics) so they can be broken again. Still hacking something up is better than waiting for inspiration to come for a rewrite, I prefer evolution to revolution but that's just me.

**Comment by irixxxx** [comment]
I found several bugs in save state handling, some even dating back to 1.93 ;-) Have a look at my save state branch. It's now saving and loading OD2 halfways OK. Save state gfx is still bad and may need more consideration.

However, saving and loading 32x seems to work for me? What have you tried?

**Comment by notaz** [comment]
Well I'm testing with RetroArch's 2 frame run-ahead and Chaotix won't boot with that. I guess loading a savestate after ADEN and all drc stuff init back to it being off doesn't go well. In other games all FM sound is trashed so `YM2612PicoStateSave2()` is far from good enough... OD2 played to completion but it's audio crashed at the beginning outputing sine wave, similar to how it used to be when OD2 came out.

**Comment by YoshiRulz** [comment]
> After reading [this post](https://github.com/TASEmulators/BizHawk/issues/2898#issuecomment-908640131) it's quite clear why TAS people don't want to update the core - savestate handling in the core is poor. While making TASes they need to save/load thousands of times, and if something isn't saved they get a desync.

Not quite. A regression in savestate quality would be cause for us to revert (or not take) changes until it was fixed, but that presumes we're pulling regularly, which we're not. The main blocker to updating our fork is the time it requires of someone who knows what they're doing.
You and the user who left the linked comment are both using a Libretro version of PicoDrive, which I'm not sure is indicative of general savestate quality, but even so that wouldn't be a blocker for us to update. A re-port to BizHawk would likely use our [Waterbox](https://github.com/TASEmulators/BizHawk/tree/master/waterbox) system.

---

I apologise if some of our ultracrepidarian users have been bothering you, by the way. I try my best to talk them down from messing with emulation internals but it doesn't work on everyone.

**Comment by irixxxx** [comment]
I think I fixed loading OD2 states. The state of the ym2612 timer wasn't saved/restored. It should now play sound up to the end after loading.

**Comment by notaz** [comment]
Yeah OD2 works now (except for broken FM) but Chaotix still won't boot for me. It no longer hangs if booted with run-ahead off so that's an improvement.
There is audio crackling in OD2 from some apparently missing DAC state (checked by commenting out all FM/PSG stuff).
I think ym2612 saving has to be redone completely and saved to a new block, maybe leaving the old block load function for compatibility. I don't mind doing that, just can't tell when.

@YoshiRulz I've had a look at BizHawk's PicoDrive and it already lives in waterbox/ ? Git log shows some old issues fixed we also fixed here, which is an unfortunate duplication of work. I think we could have a bizhawk target upstream just like we have libretro (if irixxxx is not against it). I could not find much info what waterbox actually is (same sort of sandbox?) and what was the motivation for creating/using it. There is just a readme that instructs how to build it and some debugging notes and that's it, even git log doesn't tell much.

**Comment by irixxxx** [comment]
Could you please try and toggle "use 2nd instance"? It runs for me in one setting, but not in the other.

No, I'm not against handling bizhawk like libretro. I should say it depends on how much work is landing at our shoulders, and how much maintenance there is later on. @YoshiRulz can you give a rough estimate what would be required to change in the code base for interfacing?

**Comment by notaz** [comment]
Yeah 2nd instance works better since it repeatedly saves in one of the instances and repeatedly loads in another, which allows the unsaved state to naturally progress forward and avoid breaking. It took a while to get it all working in pcsx_rearmed too.

**Comment by irixxxx** [comment]
@notaz I had a glance at the YM2612 structure, and there is a pointer for DT in the FM_SLOT structure. That would somehow need refreshing after loading the complete structure. Everything else is looking pretty straightforward, I'd say.

**Comment by YoshiRulz** [comment]
> I've had a look at BizHawk's PicoDrive and it already lives in waterbox/ ? [...] I could not find much info what waterbox actually is (same sort of sandbox?) and what was the motivation for creating/using it.

Yes, our old fork does use it. It's like a sandbox in that the stack and heap are managed by a separate host—the tl;dr is we build against a modified musl libc and then all the program's allocations are magically tracked.

---

> can you give a rough estimate what would be required to change in the code base for interfacing?

The FFI for our fork is defined on the managed side by [this class](https://github.com/TASEmulators/BizHawk/blob/2.10/src/BizHawk.Emulation.Cores/Consoles/Sega/PicoDrive/LibPicoDrive.cs) and [superclass](https://github.com/TASEmulators/BizHawk/blob/2.10/src/BizHawk.Emulation.Cores/Waterbox/LibWaterboxCore.cs) and the implementations are in [bizhawk.c](https://github.com/TASEmulators/BizHawk/blob/2.10/waterbox/picodrive/bizhawk.c).
@Morilli has made [an attempt at rebasing](https://github.com/TASEmulators/BizHawk/issues/2898#issuecomment-2696356671) while keeping that same interface and, as expected, things broke. The easiest way forward is probably for us to track down which refactor(s) caused that and then adapt to them.
But were we to start from scratch, most of the FFI is "negotiable". It is effectively an adapter to our internal APIs, which are modular.

**Comment by irixxxx** [comment]
@notaz I think I found the bug. The ADEN bit was not reset when the 32x was turned off by the 68k.

On the sound, I tried last night to fix the existing save code. I mostly succeeded, at least after loading the complete ym2612 structure was about identical to the one at save time but for the lower 3 bits of the phase counter. That shouldn't matter as the mantissa only has 10 bits on the real thing anyway. It is however still not sounding right, even after turning off all filtering which might interfere.

**Comment by notaz** [comment]
After your invitation I've started my own ym2612 savestate implementation aiming for backward/forward compatibility and it being endian neutral. However I haven't got very far yet, so if you get yours working I can abandon mine.

**Comment by notaz** [comment]
Pushed my own attempt, much messier than I hoped. It leaves the old loading code alone for compatibility and does everything from scratch with new larger save bocks.  Seems to work for me, haven't noticed any issues in OD2 or Chaotix.

As for the remaining things, in Sonic1 some of the jump keys misbehave with run-ahead, not sure what's up with that.

**Comment by irixxxx** [comment]
Nice, that makes more sense wrt to portability. Similar to what other emus do as well.

I'll have a look whether I can combine those 2 for backwards compatibility with the old gph toasters. If it's creating to many problems I'll throw those out. Looking at the download numbers and the non-existing feedback about it, I guess there'd be not much resistance to that.

**Comment by irixxxx** [comment]
Cherry-picked your commit. Still needs some work to get it back to operational on GP2X, but that's a marginal issue.

**Comment by irixxxx** [comment]
I've fixed saving/loading ym2612 on GP2X, and I also reduced the size of the save states for the new save code by throwing out values which the ym2612 code restores by itself. Have a look. If you think it's OK, I'll rebase this on the master branch.

**Comment by notaz** [comment]
Hmm not really a fan of timer save code duplication. Wouldn't it be better to update `OPN.ST.mode` on both 920/940 sides (it's needed for normal timer operation after all?) and use the new timer save block on gp2x too?

The size reduction looks good. I've pushed a commit for some missing ioports bits. I'm undecided if `PicoIn.padInt` and `PicoIn.mouseInt` should be saved or not. The save could be made in the middle of the game reading ioports and on load part of the buttons could be "more recent" which in some cases might be desirable. Or maybe not, maybe you'll have a better idea. Other than that everything seems to work with run-ahead now (very limited testing though).

**Comment by irixxxx** [comment]
I must admit I haven't given it much thought. But separating the timer code should be easily possible.

I'm thinking about a printf/scanf like interface to the save/load functions. Have "bhwl" for the signed quantities and the upper case for unsigned would be a possibility, and it would make the save/load code much more compact.

I'll look at your latest. Not sure if it's a good idea to save the internal input stuff. IIRC it should be regenerated from the input interface anyway, and isn't that done before running the first frame after loading?

**Comment by irixxxx** [comment]
I tried to add mouse to libretro in a quickshot, by just polling the mouse coordinates in the input handling. That doesn't seem to be enough, the returned coordinates just stay the same. This needs to wait until I have more time than a little break.

**Comment by irixxxx** [comment]
I'm meanwhile convinced that mousInt should also be in the save state. It is used to cache the mouse pointer values during readout through the input port. Reading would fail if it spills over into the next frame (i.e. over the save state boundary), since the cached values wouldn't be valid if not loaded from the state.

**Comment by irixxxx** [comment]
I cherry-picked your latest commit and added padInt and mouseInt.
However, looking at that code I think it should be refactored. Part of the data is in Pico.m, another part in static variables, and a third part in PicoIn...

**Comment by irixxxx** [comment]
@notaz is there anything you can think off left to handle in this issue?

**Comment by irixxxx** [comment]
So be it. merged into master.

**Comment by irixxxx** [comment]
Hmm, I think the PSG might not be properly saved too? Besides, I haven't even checked the 8 bit consoles. I reckon there might be some additional work in this :-/

**Comment by irixxxx** [comment]
I've fixed it for SMS, and for the FM unit as well. Have you tried some MCD titles?

**Comment by notaz** [comment]
No I haven't. Worth trying games using scale hw and cd+32x as well, but maybe not today.

**Comment by irixxxx** [comment]
I tried running the CD BIOS in retroarch with run-ahead last night, and that seemed to work OK. AFAIK it uses the scaler hardware, so that should be OK. playing an audio CD through the embedded player in BIOS actually didn't work well. Audio is distorted. I reckon that is because on save/load, the index into the currently playing lba isn't saved anywhere.

**Comment by irixxxx** [comment]
I looked into the CDDA code, and I believe this could never have run properly in the run-ahead scenario:
- loading a state would start the next frame at the current lba. However, since we have 75 lba/s, but only 60 fps (or 50 FWIW), this would only match every 3 or 4 frames. In the other frames, there would be an offset which is currently ignored
- there is no handling of the in-frame offset for the start of the audio data. If the code recognizes audio is playing, the whole frame would be mixed with CDDA audio, which is wrong

I have a small band-aid for testing the first topic wth WAV files, and it indeed improves, but is far from perfect. The second is IMHO harder to address. It would require sync to cycle capabilities for the CDDA audio playback, which just isn't there ATM.

**Comment by notaz** [comment]
In PCSX I'm reusing the same mechanism which determines when to send data sectors, just send the them for audio mixing. I don't remember how it's done in PD, probably it was intentionally decoupled to do mp3 decoding on secondary CPUs on GP2X and PSP. Now that cue/bin/mp3 images fell out of fashion it can maybe be dropped.

**Comment by irixxxx** [comment]
In PD it's unfortunately largely decoupled. I've pushed a commit which tries to synchronize the audio playout with the 75Hz cdd irq. Have a look.

**Comment by irixxxx** [comment]
I've fixed some more problems around mcd and 32xcd games. However, out of around 30 I tested, there are 2 still having problems, Jaguar xc 220 (main game graphics completely missing), and Batman returns (screen flicker in some places in intro). IMHO it must be related to gfx, but I have yet to find out what's going on. Any ideas?
